language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison libcurl4-openssl-dev libmarkdown2-dev
env:
  - HTTPD_VERSION=httpd-2.4.43
    APR=apr-1.7.0
    APR_UTIL=apr-util-1.6.1
    HTTPD_CONFIG_OPT=
before_script:
  - echo "HTTPD_VERSION=${HTTPD_VERSION}" > httpd_version
  - echo "APR=${APR}" >> httpd_version
  - echo "APR_UTIL=${APR_UTIL}" >> httpd_version
  - echo "HTTPD_CONFIG_OPT='${HTTPD_CONFIG_OPT}'" >> httpd_version
script:
  - sh test.sh
